"""KH03 ingest and the shared external-archive machinery, on SYNTHETIC fixtures.

The workbooks in tests/fixtures/kh03_*.xlsx are generated by make_external_fixtures.py:
invented organisations and numbers laid out like the three real title-block/header
layouts (2010-11 status line; 2013-14 to 2022-23 'Published:' rows; 2023-24 on with the
Data Quality sheet first). Network access is faked throughout.
"""
from datetime import date, datetime, timezone
from pathlib import Path

import numpy as np
import pandas as pd
import pytest
import requests
from openpyxl import load_workbook

from nhs_ae.ingest import external, kh03
from nhs_ae.ingest.download import read_manifest
from nhs_ae.ingest.external import (
    Link,
    canonical_url,
    parse_date,
    resolve_published,
    upload_month,
)
from nhs_ae.ingest.recover import PageCapture

FIX = Path(__file__).parent / "fixtures"
STATUS_LINE = FIX / "kh03_status_line.xlsx"
PUBLISHED_FIELD = FIX / "kh03_published_field.xlsx"
PERIOD_END = FIX / "kh03_period_end.xlsx"
UP = "https://www.england.nhs.uk/statistics/wp-content/uploads/sites/2/"


# --------------------------------------------------------------------------------------
# Shared helpers (external.py)
# --------------------------------------------------------------------------------------
@pytest.mark.parametrize("value, expected", [
    ("20th August 2026", date(2026, 8, 20)),
    ("21st May 2020", date(2020, 5, 21)),
    ("22nd May 2014", date(2014, 5, 22)),
    (datetime(2024, 6, 19, tzinfo=timezone.utc), date(2024, 6, 19)),
    (pd.Timestamp("2022-05-11"), date(2022, 5, 11)),
    ("2024-06-19 00:00:00", date(2024, 6, 19)),
    ("18.11.2021", date(2021, 11, 18)),
    ("25.11.25", date(2025, 11, 25)),
    ("-", None), ("", None), (None, None), (float("nan"), None),
])
def test_parse_date(value, expected):
    assert parse_date(value) == expected


def test_upload_month_and_canonical_url():
    assert upload_month(UP + "2023/05/x.xlsx") == date(2023, 5, 1)
    assert upload_month("https://example.org/x.xlsx") is None
    assert canonical_url("http://www.england.nhs.uk:80/a/b.xls?x=1#y") == \
        "https://www.england.nhs.uk/a/b.xls"


def test_resolve_published_trusts_stated_dates_inside_upload_month():
    # original: Published date, uploaded that month
    assert resolve_published(date(2024, 5, 23), None, None, date(2024, 5, 1), None) == \
        (date(2024, 5, 23), "title_block_published")
    # revision: the file's Revised date wins over Published and the link text
    assert resolve_published(date(2016, 8, 18), date(2017, 11, 23), date(2017, 11, 20),
                             date(2017, 11, 1), date(2018, 1, 4)) == \
        (date(2017, 11, 23), "title_block_revised")
    # no title dates: the revision date in the link text
    assert resolve_published(None, None, date(2025, 11, 25), date(2025, 11, 1), None) == \
        (date(2025, 11, 25), "link_text_revised")


def test_resolve_published_reuploads_are_dated_by_upper_bounds():
    # Revised 19 June 2024, but the bytes sit in the 2024/07 folder: not public in June
    d, why = resolve_published(date(2024, 5, 23), date(2024, 6, 19), None,
                               date(2024, 7, 1), date(2024, 7, 25))
    assert d == date(2024, 7, 25) and why.startswith("first_page_capture")
    assert "precedes upload folder 2024-07" in why
    # ... and with no Archive sighting, the end of the upload month
    d, why = resolve_published(date(2020, 5, 21), date(2020, 11, 19), None,
                               date(2023, 5, 1), None)
    assert d == date(2023, 5, 31) and why.startswith("upload_month_end")
    # a sighting before the upload month is ignored (it cannot be these bytes)
    d, _ = resolve_published(None, None, None, date(2023, 5, 1), date(2021, 1, 1))
    assert d == date(2023, 5, 31)
    assert resolve_published(None, None, None, None, None) == (None, "unknown")


# --------------------------------------------------------------------------------------
# Quarters and links
# --------------------------------------------------------------------------------------
def test_quarter_helpers():
    assert kh03.quarter_start(2023, 1) == date(2023, 4, 1)
    assert kh03.quarter_start(2023, 3) == date(2023, 10, 1)
    assert kh03.quarter_start(2023, 4) == date(2024, 1, 1)
    assert kh03.quarter_end(date(2023, 10, 1)) == date(2023, 12, 31)
    assert kh03.quarter_end(date(2024, 1, 1)) == date(2024, 3, 31)
    assert kh03.fy_quarter(date(2024, 1, 1)) == "2023-24 Q4"
    assert kh03.fy_quarter(date(2026, 4, 1)) == "2026-27 Q1"


@pytest.mark.parametrize("href, text, period, revised", [
    ("2025/11/Beds-Open-Overnight-Web_File-Q1-2025-26-revised.xlsx",
     "NHS organisations in England, Quarter 1, 2025-26 (revised 25.11.2025)",
     date(2025, 4, 1), date(2025, 11, 25)),
    ("2026/08/NHS-organisations-in-England-Quarter-1-2026-27-Overnight.xlsx",
     "NHS organisations in England, Quarter 1, 2026-27 – Overnight", date(2026, 4, 1), None),
    # filename-only forms seen in the upload folders
    ("2023/05/1920-Q4-Beds-Open-Overnight-Web_File-Final-DE5WC.xlsx", "", date(2020, 1, 1),
     None),
    ("2019/11/Beds-Open-Overnight-Web_File-Final-Q3-201819.xlsx", "", date(2018, 10, 1), None),
    ("2019/05/Beds-Open-Overnight-Q2-201819-REVISED-Web_File-Final.xlsx", "",
     date(2018, 7, 1), None),
    ("2019/05/Beds-Open-Overnight-Web_File-Final_Q4_2018-19.xlsx", "", date(2019, 1, 1), None),
    ("2013/04/Beds-Open-Overnight-Web_File-Q4-2015-16-Revised-Aug16-Final-84398.xlsx", "",
     date(2016, 1, 1), None),
    ("2013/04/NHS-organisations-in-England-Quarter-4-2010-11-XLS-393K.xls",
     "NHS organisations in England, Quarter 4, 2010-11 (XLS, 393K)", date(2011, 1, 1), None),
])
def test_parse_link(href, text, period, revised):
    link = kh03.parse_link(UP + href, text)
    assert link is not None and link.period == period and link.revised_on == revised
    assert link.filename == href.split("/")[-1]


@pytest.mark.parametrize("href, text", [
    ("2013/04/Download-–-NHS-Organisations-in-England-2009-10-XLS-416K1.xls",
     "Download – NHS Organisations in England, 2009-10 (XLS, 416K)"),   # annual, pre-2010-11
    ("2026/08/Beds-Timeseries-2010-11-onwards-Q1-2026-27.xlsx", "Beds-Timeseries"),
    ("2024/09/KH03-Available-Overnight-only.csv", "KH03 Available Overnight only"),
    ("2026/08/Beds-Open-Day-Only-Web_File-Q1-2026-27.xlsx",
     "NHS organisations in England, Quarter 1, 2026-27 – Day only"),
    ("2023/11/2023-24-Q2-Bed-availability-and-occupancy-PRA-for-pub.pdf", "PRA"),
])
def test_parse_link_rejects_other_files(href, text):
    assert kh03.parse_link(UP + href, text) is None


def test_extract_links_dedupes_and_resolves_relative_hrefs():
    html = ('<a href="/statistics/wp-content/uploads/sites/2/2026/05/'
            'Beds-Open-Overnight-Web_File-Q4-2025-26.xlsx">NHS organisations in England, '
            'Quarter 4, 2025-26</a><a href="' + UP + '2026/05/Beds-Open-Overnight-Web_File-'
            'Q4-2025-26.xlsx">again</a><a href="/other.pdf">pdf</a>')
    links = kh03.extract_links(html, kh03.PAGE_URL)
    assert len(links) == 1
    assert links[0].url.startswith("https://www.england.nhs.uk/statistics/wp-content/")
    assert links[0].period == date(2026, 1, 1)


# --------------------------------------------------------------------------------------
# Workbook layouts
# --------------------------------------------------------------------------------------
def test_read_status_line_layout():
    f = kh03.read_kh03(STATUS_LINE)
    assert (f.published, f.revised) == (date(2010, 11, 18), date(2012, 5, 24))
    assert f.quarter == date(2010, 4, 1)
    assert f.layout == "xlsx|status_line|sha code|period"
    rows = f.rows.set_index("org_code")
    assert list(rows.index) == ["ENG", "ZZ1", "ZZA", "ZZB"]  # PCT kept, footnote dropped
    assert rows.loc["ENG", "is_total"] and not rows.loc["ZZA", "is_total"]
    assert rows.loc["ZZA", "ga_available"] == 360 and rows.loc["ZZA", "ga_occupied"] == 320
    assert rows.loc["ZZA", "ga_occupancy"] == pytest.approx(320 / 360)
    assert np.isnan(rows.loc["ZZ1", "ga_occupancy"])  # '-' for a PCT with no G&A beds
    assert rows.loc["ZZA", "parent_code"] == "Q90"
    assert f.dq == {}  # names only in this era's Data Quality sheet, no codes


def test_read_published_field_layout():
    f = kh03.read_kh03(PUBLISHED_FIELD)
    assert (f.published, f.revised) == (date(2016, 8, 18), date(2017, 11, 23))
    assert f.quarter == date(2016, 4, 1)
    assert f.layout == "xlsx|published_field|region code|period"
    assert f.dq == {"ZZB": "revised_return"}
    eng = f.rows[f.rows.is_total].iloc[0]
    trusts = f.rows[~f.rows.is_total]
    assert eng.ga_occupied == trusts.ga_occupied.sum()


def test_read_period_end_layout_with_quality_sheet_first():
    f = kh03.read_kh03(PERIOD_END.read_bytes())  # bytes work as well as paths
    assert (f.published, f.revised) == (date(2024, 5, 23), date(2024, 6, 19))
    assert f.quarter == date(2024, 1, 1)
    assert f.layout.endswith("|period end")
    assert f.dq == {"ZZC": "estimate_on_behalf"}
    zzc = f.rows.set_index("org_code").loc["ZZC"]
    assert zzc.ga_available == 0 and np.isnan(zzc.ga_occupancy) and zzc.total_available == 90


def test_percentage_occupancy_is_rescaled(tmp_path):
    wb = load_workbook(PUBLISHED_FIELD)
    ws = wb["NHS Trust by Sector"]
    for row in ws.iter_rows(min_row=16):
        for c in row[18:23]:
            if isinstance(c.value, float):
                c.value = c.value * 100
    p = tmp_path / "pct.xlsx"
    wb.save(p)
    f = kh03.read_kh03(p)
    assert f.rows.ga_occupancy.max() < 1.0


def test_day_only_table_is_rejected(tmp_path):
    wb = load_workbook(PUBLISHED_FIELD)
    wb["NHS Trust by Sector"]["C2"] = "Average daily number of beds open day only by sector"
    p = tmp_path / "dayonly.xlsx"
    wb.save(p)
    with pytest.raises(ValueError, match="overnight"):
        kh03.read_kh03(p)


# --------------------------------------------------------------------------------------
# Build: versions, re-uploads, as-of
# --------------------------------------------------------------------------------------
def _variant(tmp_path: Path, name: str, published: str, revised, bump: float = 0.0) -> Path:
    """The published-field fixture with new title dates and ZZA's G&A occupied changed."""
    wb = load_workbook(PUBLISHED_FIELD)
    ws = wb["NHS Trust by Sector"]
    ws["C8"], ws["C9"] = published, revised
    for row in ws.iter_rows(min_row=16):
        if row[4].value == "ZZA":
            row[13].value = row[13].value + bump
    p = tmp_path / "data" / "external" / "kh03" / "raw" / name
    p.parent.mkdir(parents=True, exist_ok=True)
    wb.save(p)
    return p


def _manifest(tmp_path: Path, records: list[dict]) -> Path:
    path = tmp_path / "data" / "external" / "kh03" / "raw" / "manifest.jsonl"
    for r in records:
        external.append_jsonl(r, path)
    return path


def test_build_orders_versions_drops_reuploads_and_supports_as_of(tmp_path):
    orig = _variant(tmp_path, "orig.xlsx", "18th August 2016", None)
    rev = _variant(tmp_path, "rev.xlsx", "18th August 2016", "23rd November 2017", bump=5)
    reup = _variant(tmp_path, "reup.xlsx", "18th August 2016", "23rd November 2017", bump=5)
    broken = tmp_path / "data" / "external" / "kh03" / "raw" / "broken.xlsx"
    broken.write_bytes(b"not a workbook")

    def rec(p, url, published, why="title_block_published"):
        return {"url": url, "filename": p.name, "period": "2016-04-01", "stored": True,
                "sha256": p.name, "path": str(p.relative_to(tmp_path)),
                "published": published, "published_source": why}

    manifest = _manifest(tmp_path, [
        rec(orig, UP + "2016/08/orig.xlsx", "2016-08-18"),
        rec(rev, UP + "2017/11/rev.xlsx", "2017-11-23", "title_block_revised"),
        rec(reup, UP + "2023/05/reup.xlsx", "2023-05-31", "upload_month_end"),
        rec(broken, UP + "2017/11/broken.xlsx", "2017-11-23"),
        {"url": UP + "gone.xlsx", "error": "gone", "stored": False},
    ])
    df, failures = kh03.build(manifest, tmp_path, out_path=None)
    assert len(failures) == 1 and failures.iloc[0].source_file == "broken.xlsx"
    assert sorted(df.source_file.unique()) == ["orig.xlsx", "rev.xlsx"]  # re-upload dropped
    assert set(df.fy_quarter) == {"2016-17 Q1"}
    assert (df.quarter_end == pd.Timestamp("2016-06-30")).all()
    assert (df.first_published == pd.Timestamp("2016-08-18")).all()
    v = df.drop_duplicates("source_file").set_index("source_file")
    assert v.loc["orig.xlsx", "version"] == 1 and not v.loc["orig.xlsx", "is_latest"]
    assert v.loc["rev.xlsx", "version"] == 2 and v.loc["rev.xlsx", "is_latest"]
    assert (df.n_versions == 2).all()
    zza = df[df.org_code == "ZZA"].set_index("version").ga_occupied
    assert zza[2] - zza[1] == 5
    assert df.loc[df.org_code == "ZZB", "dq_flag"].iloc[0] == "revised_return"

    def zza_on(when, **kw):
        cur = kh03.as_of(df, when, **kw)
        return cur.loc[cur.org_code == "ZZA", "ga_occupied"].tolist()

    assert zza_on("2016-08-17") == []
    assert zza_on("2016-08-18") == [zza[1]]
    assert zza_on("2017-11-22") == [zza[1]]
    assert zza_on("2017-11-23") == [zza[2]]
    assert zza_on("2016-09-01", use_first_published=True) == [zza[2]]  # the leaky shortcut

    vt = kh03.versions(df).set_index("version")
    assert list(vt.fy_quarter.unique()) == ["2016-17 Q1"]
    assert vt.loc[1, "lag_days"] == 49 and vt.loc[2, "lag_days"] == 511  # after 30 June 2016
    assert vt.loc[2, "orgs_changed"] == 1 and vt.loc[2, "orgs_added"] == 0
    assert np.isnan(vt.loc[1, "orgs_changed"])


def test_build_writes_parquet(tmp_path):
    p = _variant(tmp_path, "one.xlsx", "18th August 2016", None)
    manifest = _manifest(tmp_path, [{
        "url": UP + "2016/08/one.xlsx", "filename": "one.xlsx", "period": "2016-04-01",
        "stored": True, "sha256": "x", "path": str(p.relative_to(tmp_path)),
        "published": "2016-08-18", "published_source": "title_block_published"}])
    out = tmp_path / "processed" / "kh03.parquet"
    kh03.build(manifest, tmp_path, out_path=out)
    back = pd.read_parquet(out)
    assert list(back.columns[:6]) == ["quarter_start", "quarter_end", "fy_quarter", "org_code",
                                      "org_name", "parent_code"]
    assert back.published.dtype.kind == "M"
    assert (out.parent / "kh03_parse_failures.csv").exists()
    assert len(pd.read_csv(out.parent / "kh03_versions.csv")) == 1


# --------------------------------------------------------------------------------------
# collect(): discovery through live page, Archive page history and upload index
# --------------------------------------------------------------------------------------
class _Resp:
    def __init__(self, status: int, content: bytes = b""):
        self.status_code, self.content = status, content

    def raise_for_status(self):
        if self.status_code >= 400:
            raise requests.HTTPError(str(self.status_code), response=self)


class FakeNHS:
    def __init__(self, pages: dict[str, str], files: dict[str, bytes]):
        self.pages, self.files, self.calls = pages, files, []

    def get(self, url, **kw):
        self.calls.append(url)
        if url in self.pages:
            return _Resp(200, self.pages[url].encode())
        if url in self.files:
            return _Resp(200, self.files[url])
        return _Resp(404)


class FakeWayback:
    """Page captures, an upload index and file captures, all in memory."""

    def __init__(self, captures: dict[str, list[tuple[str, str]]], index: list[str],
                 files: dict[str, bytes]):
        self.captures, self.index, self.files = captures, index, files

    def cdx(self, params):
        url = params["url"]
        if params.get("matchType") == "prefix":
            return [["20240101000000", u] for u in self.index if url in u]
        for page, caps in self.captures.items():
            if page.split("://", 1)[-1] == url:
                return [[ts, page, f"D{ts}"] for ts, _ in caps]
        return [["20200101000000"]] if any(url in u for u in self.files) else []

    def fetch_capture(self, cap: PageCapture) -> str:
        return dict(self.captures[cap.url])[cap.timestamp]

    def fetch_file(self, url, ts):
        return self.files[url]


def _page(links: list[tuple[str, str]]) -> str:
    return "<html><body>" + "".join(f'<a href="{u}">{t}</a>' for u, t in links) + "</body></html>"


def test_collect_finds_superseded_and_gone_versions(tmp_path):
    orig_url = UP + "2016/08/Beds-Open-Overnight-Web_File-Q1-2016-17.xlsx"
    rev_url = UP + "2017/11/Beds-Open-Overnight-Web_File-Q1-2016-17-Final-98123.xlsx"
    gone_url = UP + "2016/09/Beds-Open-Overnight-Web_File-Q1-2016-17-v2.xlsx"
    label = "NHS organisations in England, Quarter 1, 2016-17"
    orig = _variant(tmp_path, "o.xlsx", "18th August 2016", None).read_bytes()
    rev = _variant(tmp_path, "r.xlsx", "18th August 2016", "23rd November 2017", 5).read_bytes()
    nhs = FakeNHS(
        pages={kh03.PAGE_URL: _page([(rev_url, label + " (revised 23.11.2017)")])},
        files={orig_url: orig, rev_url: rev})  # gone_url is no longer served
    wb = FakeWayback(
        captures={kh03.PAGE_URL: [("20160901000000", _page([(orig_url.replace(
            "https://", "http://"), label)])), ("20171201000000", _page([(rev_url, label)]))]},
        index=[gone_url], files={gone_url: orig})
    raw = tmp_path / "data" / "external" / "kh03" / "raw"
    spec = external.SourceSpec(
        name="kh03", pages=(kh03.PAGE_URL,), raw_dir=raw, manifest_path=raw / "manifest.jsonl",
        project_root=tmp_path, extract_links=kh03.extract_links,
        link_from_url=kh03.link_from_url, read_dates=kh03.read_dates, index_years=(2016,),
        index_regex=kh03.INDEX_REGEX)
    summary = external.collect(spec, fetcher=external.Fetcher(nhs, delay=0), wayback=wb)
    assert summary["urls"] == 3 and summary["failed"] == 0
    assert summary["stored"] == 2 and summary["duplicates"] == 1  # gone_url == orig bytes

    m = {r["url"]: r for r in read_manifest(raw / "manifest.jsonl")}
    assert m[orig_url]["first_seen"] == "2016-09-01" and not m[orig_url]["on_live_page"]
    assert m[orig_url]["published"] == "2016-08-18"
    assert m[orig_url]["published_source"] == "title_block_published"
    assert m[rev_url]["on_live_page"] and m[rev_url]["published"] == "2017-11-23"
    assert m[rev_url]["link_revised"] == "2017-11-23"
    assert m[gone_url]["fetched_from"].startswith("wayback:")
    assert m[gone_url]["stored"] is False and "identical_to" in m[gone_url]

    # A second run fetches only the live page's files again (in-place replacement check).
    nhs.calls.clear()
    summary = external.collect(spec, fetcher=external.Fetcher(nhs, delay=0), wayback=wb)
    assert summary["skipped"] == 2 and summary["fetched"] == 1
    assert rev_url in nhs.calls and orig_url not in nhs.calls

    df, failures = kh03.build(raw / "manifest.jsonl", tmp_path, out_path=None)
    assert failures.empty and sorted(df.version.unique()) == [1, 2]
    assert external.manifest_versions(read_manifest(raw / "manifest.jsonl"))[0]["urls"]


def test_merge_sighting_canonicalises_url_and_keeps_revision_label():
    s: dict = {}
    external.merge_sighting(s, Link("http://www.england.nhs.uk/x.xlsx", "x.xlsx",
                                    date(2020, 1, 1), "plain"))
    external.merge_sighting(s, Link("https://www.england.nhs.uk/x.xlsx", "x.xlsx",
                                    date(2020, 1, 1), "revised", date(2020, 11, 19)))
    (only,) = s.values()
    assert only.link.revised_on == date(2020, 11, 19) and only.labels == ["plain", "revised"]
