"""Render the pre-registration's amendment table as a readable log.

The audit trail is the product (work order, Stage I2), but §10 of
`docs/preregistration.md` is a three-column markdown table whose cells run to
several hundred words, which no reader can follow. This turns it into one entry
per amendment, in order, with the change and the reason reproduced **verbatim**.

Nothing is summarised, reordered or dropped: the only edits are formatting
(table cell to paragraphs, escaped pipes unescaped). The labels on each entry
are derived mechanically from the row's own words, and the rule for each is
printed in the output.

Usage: python tools/render_amendment_log.py [--check]
  --check exits 1 if docs/amendment_log.md is not what this script would write.
"""
from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "docs" / "preregistration.md"
TARGET = ROOT / "docs" / "amendment_log.md"
HEADING = "## 10. Amendments"
CELL = re.compile(r"(?<!\\)\|")
DATE = re.compile(r"\d{4}-\d{2}-\d{2}")
TITLE = re.compile(r"^\*\*(?P<title>.+?)\*\*(?P<rest>.*)$", re.S)

# label -> (test on the row's own text, the rule as printed)
LABELS: list[tuple[str, callable, str]] = [
    ("describes a result", lambda s, c, r: "[describes a result]" in c,
     'the row marks itself *[describes a result]*'),
    ("written before the result", lambda s, c, r: "before any" in f"{s} {c}",
     '"before any …" appears in the date or change cell'),
    ("Ellie's decision", lambda s, c, r: "Ellie" in f"{c} {r}",
     '"Ellie" appears in the change or reason cell'),
    ("pre-freeze", lambda s, c, r: "pre-freeze" in s,
     '"pre-freeze" appears in the date cell'),
]


def rows(text: str) -> list[tuple[str, str, str]]:
    """Every data row of §10's table, as (date cell, change cell, reason cell)."""
    lines = text.splitlines()
    start = next(i for i, l in enumerate(lines) if l.strip() == HEADING)
    end = next((i for i, l in enumerate(lines[start + 1:], start + 1)
                if re.match(r"#{1,6} ", l)), len(lines))
    out = []
    for line in lines[start:end]:
        if not line.startswith("|"):
            continue
        raw = CELL.split(line.strip())[1:-1]     # split on unescaped pipes only
        if raw[0].strip() in ("Date", "---") or set(raw[0].strip()) <= {"-", ":"}:
            continue
        if len(raw) < 3:                         # never skip a row in silence
            raise ValueError(f"amendment row with {len(raw)} cells: {line[:80]}")
        # §10 writes |x - y| in places, and those pipes split the change cell. The
        # first cell is always the date and the last the reason, so rejoin the rest,
        # spacing included, as the change.
        cells = (raw[0], "|".join(raw[1:-1]), raw[-1])
        out.append(tuple(c.strip().replace(r"\|", "|") for c in cells))
    undated = [c[0] for c in out if not DATE.search(c[0])]
    if undated:                                  # a row this parser does not understand
        raise ValueError(f"amendment rows without a date: {undated}")
    return out


def split_title(change: str) -> tuple[str | None, str]:
    """A leading bold span is the amendment's title; the rest is its body.

    Lossless: ``f"**{title}**{body}" == change.strip()`` whenever a title is found,
    so the entry still reproduces the whole cell, heading and paragraph together.
    """
    m = TITLE.match(change.strip())
    if not m:
        return None, change.strip()
    return m.group("title"), m.group("rest")


def render(amendments: list[tuple[str, str, str]], commit: str) -> str:
    dates = [DATE.search(stamp).group() for stamp, _, _ in amendments]
    labelled = [[name for name, test, _ in LABELS if test(s, c, r)] for s, c, r in amendments]
    counts = {name: sum(name in got for got in labelled) for name, _, _ in LABELS}

    out = [
        "# The amendment log, in full",
        "",
        "> Generated by `tools/render_amendment_log.py` from §10 of `docs/preregistration.md`",
        f"> at commit `{commit}`. **Do not edit by hand**; edit the pre-registration and",
        "> re-run `make amendments`. Every change and reason below is reproduced verbatim;",
        "> only the formatting differs.",
        "",
        "The pre-registration was frozen on 2026-09-09 as the tag `prereg-v1`. Everything",
        "decided after that is here, with its date and its reason — including the decisions",
        "that went against the plan, the corrections to my own earlier statements, and the",
        "rows written after a result was seen, which say so in their own text. The log is the",
        "evidence that the confirmatory claims were fixed before the sealed data were opened;",
        "it is meant to be read adversarially.",
        "",
        "## How to read it",
        "",
        f"There are **{len(amendments)} amendments**, from {min(dates)} to {max(dates)}.",
        "Each entry carries labels derived mechanically from the row's own words, not from a",
        "judgement made here:",
        "",
    ]
    for name, _, rule in LABELS:
        out.append(f"- **{name}** — {rule} ({counts[name]} of {len(amendments)}).")
    out += [
        "",
        "An entry with no label is a plain change to the registered design, recorded before",
        "the work it governs. The labels are not exclusive: a decision taken after a result",
        "was seen carries both.",
        "",
        "By date:",
        "",
        "| Date | Amendments |",
        "|---|---|",
    ]
    for date in sorted(set(dates)):
        out.append(f"| {date} | {dates.count(date)} |")
    out += ["", "## The amendments", ""]

    for n, ((stamp, change, reason), labels) in enumerate(zip(amendments, labelled), 1):
        title, body = split_title(change)
        head = f"### {n}. {stamp}" + (f" — {title.strip().rstrip('.')}" if title else "")
        out += [head, ""]
        if labels:
            out += ["*" + " · ".join(labels) + "*", ""]
        out += ["**Change.** " + body.strip(), "", "**Reason.** " + reason, ""]
    return "\n".join(out) + "\n"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="exit 1 if the target is stale")
    args = ap.parse_args(argv)

    commit = subprocess.run(["git", "rev-parse", "--short", "HEAD"], cwd=ROOT,
                            capture_output=True, text=True, check=False).stdout.strip() or "unknown"
    text = render(rows(SOURCE.read_text()), commit)
    if args.check:
        current = TARGET.read_text() if TARGET.exists() else ""
        # the commit line moves with every commit; compare everything else
        strip = lambda s: "\n".join(l for l in s.splitlines() if not l.startswith("> at commit"))
        if strip(current) != strip(text):
            print(f"{TARGET.relative_to(ROOT)} is stale; run: make amendments", file=sys.stderr)
            return 1
        print(f"{TARGET.relative_to(ROOT)} is up to date")
        return 0
    TARGET.write_text(text)
    print(f"wrote {TARGET.relative_to(ROOT)} ({len(text.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
